name: Test publish (testpypi)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          bash dev/setup.sh --deps "development"
      - name: Test publish
        env:
          HATCH_PYPI_USER: __token__
          HATCH_PYPI_PASS: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: bash dev/publish.sh "testpypi"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
